### ISSUE TITLE
OSError when kicking off DM workflow

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#130]
From #127, ran for about four hours, ending with this (probably the same error):

```
D Wed-04:16:25 - after count()
HDF5 workflow file name: /home/8-id-i/2020-1/bluesky/A923/A923_0001-0100.hdf
I Wed-04:16:48 - creating HDF5 file /home/8-id-i/2020-1/bluesky/A923/A923_0001-0100.hdf
I Wed-04:16:48 - DM workflow kickoff starting: analysis:True  file:/home/8-id-i/2020-1/bluesky/A923/A923_0001-0100.hdf
I Wed-04:16:48 - self.QMAP_FOLDER_PATH=/home/8-id-i/partitionMapLibrary/2020-1
I Wed-04:16:48 - self.XPCS_QMAP_FILENAME=Lambda_qmap.h5
I Wed-04:16:48 - DM Workflow call is made for XPCS Analysis: /home/8-id-i/2020-1/bluesky/A923/A923_0001-0100.hdf,  /home/8-id-i/partitionMapLibrary/2020-1/Lambda_qmap.h5  ----2020-01-29 04:16:48.816385
Exception in thread Thread-48425:
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/50-controls.py", line 1044, in kickoff_DM_workflow
    out, err = dm_workflow.DataAnalysis(hdf_workflow_file)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/spec_support/APS_DM_8IDI.py", line 701, in DataAnalysis
    return unix(cmd)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/spec_support/APS_DM_8IDI.py", line 59, in unix
    stderr = subprocess.PIPE,
  File "/home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory

I Wed-04:16:48 - AD_Acquire starting
I Wed-04:16:48 - file_path = /home/8-id-i/2020-1/bluesky/A924/
I Wed-04:16:48 - Shutter will *REMAIN OPEN THROUGH* the Acquisition...
I Wed-04:16:48 - calling full_acquire_procedure()
D Wed-04:16:48 - before update_metadata_prescan()
I Wed-04:16:48 - detNum=25, det_pars={'ccdHardwareRowSize': 516, 'ccdHardwareColSize': 1556, 'ccdxsense': 1, 'ccdzsense': 1, 'harmonic': 1, 'dpix': 0.055, 'saturation': 4095, 'adupphot': 1.0, 'efficiency': 1.0, 'gain': 1, 'blemish': 1, 'flatfield': 1, 'distortion': 0, 'parasitic': 0, 'lld': 0, 'manufacturer': 'LAMBDA'}
D Wed-04:16:49 - after update_metadata_prescan()
I Wed-04:16:49 - scaler should be autocounting now
D Wed-04:16:49 - before count()
Transient Scan ID: 1295     Time: 2020/01/29 04:16:49
Persistent Unique Scan ID: 'f42ebd10-a5a8-4f25-aa0c-e948c2bbae1c'
New stream: 'baseline'
Start-of-run baseline readings:
+--------------------------------+--------------------------------+
+--------------------------------+--------------------------------+
New stream: 'Timebase_monitor'
New stream: 'pind1_monitor'
New stream: 'pind2_monitor'
New stream: 'Atten1_monitor'
New stream: 'Atten2_monitor'
New stream: 'lakeshore_loop1_temperature_monitor'
New stream: 'lakeshore_loop1_target_monitor'
I Wed-04:17:09 - full_name: /home/8-id-i/2020-1/bluesky/A924/A924_00001-00100.imm
closure() method endss. No progress bar available.]
cam.acquire.value=0
immout.capture.value=0
immout.num_captured.value=100
status=DeviceStatus(device=lambdadet, done=True, success=True)
New stream: 'primary'
+-----------+------------+
|   seq_num |       time |
+-----------+------------+
|         1 | 04:17:21.1 |
+-----------+------------+
generator lambda_test ['f42ebd10'] (scan num: 1295)
End-of-run baseline readings:
+--------------------------------+--------------------------------+
+--------------------------------+--------------------------------+



D Wed-04:17:24 - after count()
/home/beams/8IDIUSER/bin/bluesky8IDI: line 40: 21128 Killed                  ipython --profile=${IPYTHON_PROFILE} --ipython-dir=${IPYTHON_DIR} --IPCompleter.use_jedi=False
```

Focus on this part:

```
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/spec_support/APS_DM_8IDI.py", line 59, in unix
    stderr = subprocess.PIPE,
```

which ends in

```
OSError: [Errno 12] Cannot allocate memory
```

Looks like it is a memory leak in the code which calls *subprocess*.

_Originally posted by @prjemian in https://github.com/aps-8id-dys/ipython-8idiuser/issues/127#issuecomment-579759786_

**Comment by prjemian** [comment]
Perhaps, refactor these lines using a context (`with subprocess.Popen() as process...`: https://github.com/aps-8id-dys/ipython-8idiuser/blob/544def3ef9c49902c5537a5cd7041994d83cb21c/profile_bluesky/startup/spec_support/APS_DM_8IDI.py#L54-L70

**Comment by prjemian** [comment]
No complaints from IOC console, no OSError from bluesky in the first 100 iterations of #127, declaring victory for now
