### ISSUE TITLE
SPEC workflow helper broken this past week

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/ipython-8idiuser#137]
@sureshnaps emails:

> It turns out that the DM workflow call from SPEC using helper.py was broken in the past week. 

<details>
<summary>console output</summary>
<p>

```

8idiuser@bronze ~/.../startup/spec_support $ ./helper.py 
D Fri-17:14:53 - starting
D Fri-17:14:53 - WorkflowHelper() constructor
I Fri-17:14:53 - setting up DM_Workflow() for APS operating cycle 2020-1
I Fri-17:14:53 - runPollingLoop() starting
D Fri-17:17:19 - workflow handling triggered
I Fri-17:17:19 - calling start_workflow(analysis=0.0)
I Fri-17:17:19 - starting start_workflow(): workflow:transfer
I Fri-17:17:19 - starting start_workflow()
I Fri-17:17:19 - creating hdf_workflow_file = /home/8-id-i/2020-1/qzhang202002/A005_Aerogel_1mm_025C_att0_Lq0_001/A005_Aerogel_1mm_025C_att0_Lq0_001_0001-10000.hdf
I Fri-17:17:19 - creating HDF5 file /home/8-id-i/2020-1/qzhang202002/A005_Aerogel_1mm_025C_att0_Lq0_001/A005_Aerogel_1mm_025C_att0_Lq0_001_0001-10000.hdf
Traceback (most recent call last):
  File "./helper.py", line 50, in <module>
    spec_DM_support.main()
  File "./../spec_support/spec_DM_support.py", line 341, in main
    helper.runPollingLoop()
  File "./../spec_support/spec_DM_support.py", line 320, in runPollingLoop
    analysis=self.registers.workflow_submit_xpcs_job.value)
  File "./../spec_support/APS_DM_8IDI.py", line 262, in start_workflow
    self.create_hdf5_file(self.hdf_workflow_file)
  File "./../spec_support/APS_DM_8IDI.py", line 393, in create_hdf5_file
    if registers.geometry_num.get() == 1: ##reflection geometry
AttributeError: 'MyPV' object has no attribute 'get'
(bluesky) 8idiuser@bronze ~/.../startup/spec_support $
```

</p>
</details>

**Comment by prjemian** [comment]
See https://github.com/aps-8id-dys/ipython-8idiuser/issues/118#issuecomment-581500519

Here's one place that needs to change back.

**Comment by prjemian** [comment]
@sureshnaps emails:

> After looking at your recent [commits], I figured out the problem.

Pete: such as for #135

**Comment by prjemian** [comment]
Work on this depends on PR #135 since that PR changes the files needed to resolve this issue.
