### ISSUE TITLE
Fly Stage Timed out in Bluesky

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#171]
I was trying to test 1000 XSPA acquisitions with Bluesky and it timed out at acquisition No. 3 due to fly scan. The error message is attached. Any suggestions?

Thanks,

QZ

<details>
<summary> Error message </summary>

```
In [63]: RE(raster_acq())                                                                                                            
D Thu-13:54:44 - starting TAXI to position
D Thu-13:54:44 - starting FLY
H031_D100_att02_35p00C_0001
I Thu-13:54:44 - AD_Acquire starting
I Thu-13:54:44 - file_path = /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0001/
I Thu-13:54:44 - calling full_acquire_procedure()
D Thu-13:54:44 - before update_metadata_prescan()
I Thu-13:54:44 - detNum=46, det_pars={'ccdHardwareColSize': 512, 'ccdHardwareRowSize': 1024, 'ccdxsense': 1, 'ccdzsense': 1, 'harmonic': 1, 'dpix': 0.076, 'saturation': 3, 'adupphot': 1.0, 'efficiency': 1.0, 'gain': 1, 'blemish': 1, 'flatfield': 0, 'distortion': 0, 'parasitic': 0, 'lld': 0, 'manufacturer': 'RIGAKU500K_NoGap'}
D Thu-13:54:44 - after update_metadata_prescan()
D Thu-13:54:44 - supplied metadata = {'ARun_number': 'H031_D100_att02_35p00C_0001', 'plan_args': {'detector_name': 'rigaku', 'acquire_time': 0.1, 'acquire_period': 0.11, 'num_images': 100000, 'file_name': 'H031_D100_att02_35p00C_0001', 'submit_xpcs_job': 'True', 'path': '/home/8-id-i/2020-2/comm202006/'}}
D Thu-13:54:44 - file_name = H031_D100_att02_35p00C_0001
D Thu-13:54:44 - file_path = /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0001/
D Thu-13:54:44 - metadata = {'file_name': 'H031_D100_att02_35p00C_0001', 'file_path': '/home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0001/', 'ARun_number': 'H031_D100_att02_35p00C_0001', 'plan_args': {'detector_name': 'rigaku', 'acquire_time': 0.1, 'acquire_period': 0.11, 'num_images': 100000, 'file_name': 'H031_D100_att02_35p00C_0001', 'submit_xpcs_job': 'True', 'path': '/home/8-id-i/2020-2/comm202006/'}}
I Thu-13:54:44 - scaler should be autocounting now
D Thu-13:54:44 - before count()


Transient Scan ID: 6968     Time: 2020-06-18 13:54:44
Persistent Unique Scan ID: '0100498f-7f41-4fc6-aad6-6a2f6aaf5982'
New stream: 'baseline'
New stream: 'aps_current_monitor'
New stream: 'Timebase_monitor'
New stream: 'pind1_monitor'
New stream: 'pind2_monitor'


 folder ============= H031_D100_att02_35p00C_0001 




 fname ============= H031_D100_att02_35p00C_0001_00001-100000.bin 


H031_D100_att02_35p00C_0001/H031_D100_att02_35p00C_0001_00001-100000.bin
New stream: 'Atten1_monitor'
New stream: 'Atten2_monitor'
New stream: 'lakeshore_loop1_temperature_monitor'
New stream: 'lakeshore_loop1_target_monitor'
New stream: 'primary'                                                                                                                
+-----------+------------+
|   seq_num |       time |
+-----------+------------+
|         1 | 13:54:46.7 |
D Thu-13:54:46 - after count()
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0001/H031_D100_att02_35p00C_0001_0001-100000.hdf
+-----------+------------+
generator raster_acq ['0100498f'] (scan num: 6968)
I Thu-13:54:46 - DM workflow kickoff starting: analysis:True  file:/home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0001/H031_D100_att02_35p00C_0001_0001-100000.hdf
D Thu-13:54:47 - starting TAXI to position
D Thu-13:54:47 - starting FLY
H031_D100_att02_35p00C_0002
I Thu-13:54:47 - AD_Acquire starting
I Thu-13:54:47 - file_path = /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0002/
I Thu-13:54:47 - calling full_acquire_procedure()
D Thu-13:54:47 - before update_metadata_prescan()
I Thu-13:54:47 - detNum=46, det_pars={'ccdHardwareColSize': 512, 'ccdHardwareRowSize': 1024, 'ccdxsense': 1, 'ccdzsense': 1, 'harmonic': 1, 'dpix': 0.076, 'saturation': 3, 'adupphot': 1.0, 'efficiency': 1.0, 'gain': 1, 'blemish': 1, 'flatfield': 0, 'distortion': 0, 'parasitic': 0, 'lld': 0, 'manufacturer': 'RIGAKU500K_NoGap'}
D Thu-13:54:47 - after update_metadata_prescan()
D Thu-13:54:47 - supplied metadata = {'ARun_number': 'H031_D100_att02_35p00C_0002', 'plan_args': {'detector_name': 'rigaku', 'acquire_time': 0.1, 'acquire_period': 0.11, 'num_images': 100000, 'file_name': 'H031_D100_att02_35p00C_0002', 'submit_xpcs_job': 'True', 'path': '/home/8-id-i/2020-2/comm202006/'}}
D Thu-13:54:47 - file_name = H031_D100_att02_35p00C_0002
D Thu-13:54:47 - file_path = /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0002/
D Thu-13:54:47 - metadata = {'file_name': 'H031_D100_att02_35p00C_0002', 'file_path': '/home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0002/', 'ARun_number': 'H031_D100_att02_35p00C_0002', 'plan_args': {'detector_name': 'rigaku', 'acquire_time': 0.1, 'acquire_period': 0.11, 'num_images': 100000, 'file_name': 'H031_D100_att02_35p00C_0002', 'submit_xpcs_job': 'True', 'path': '/home/8-id-i/2020-2/comm202006/'}}
I Thu-13:54:47 - scaler should be autocounting now
D Thu-13:54:47 - before count()


Transient Scan ID: 6969     Time: 2020-06-18 13:54:47
Persistent Unique Scan ID: '195abcd6-5082-49cf-9a82-f26b19435d15'
New stream: 'baseline'
New stream: 'aps_current_monitor'
New stream: 'Timebase_monitor'


 folder ============= H031_D100_att02_35p00C_0002 

New stream: 'pind1_monitor'



 fname ============= H031_D100_att02_35p00C_0002_00001-100000.bin 


H031_D100_att02_35p00C_0002/H031_D100_att02_35p00C_0002_00001-100000.bin
New stream: 'pind2_monitor'
New stream: 'Atten1_monitor'
New stream: 'Atten2_monitor'
New stream: 'lakeshore_loop1_temperature_monitor'
New stream: 'lakeshore_loop1_target_monitor'
I Thu-13:54:47 - DM workflow kickoff done
I Thu-13:54:47 - b'id=185433fc-ff23-4246-937e-241a2805356d owner=8idiuser status=pending startTime=1592506487.51 startTimestamp=2020/06/18 13:54:47 CDT \n'
New stream: 'primary'                                                                                                                
+-----------+------------+
|   seq_num |       time |
+-----------+------------+
|         1 | 13:54:49.7 |
D Thu-13:54:49 - after count()
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0002/H031_D100_att02_35p00C_0002_0001-100000.hdf
+-----------+------------+
generator raster_acq ['195abcd6'] (scan num: 6969)
I Thu-13:54:50 - DM workflow kickoff starting: analysis:True  file:/home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0002/H031_D100_att02_35p00C_0002_0001-100000.hdf
I Thu-13:54:50 - DM workflow kickoff done
I Thu-13:54:50 - b'id=cbc20ec6-f1c7-4041-ae6a-18a866710447 owner=8idiuser status=pending startTime=1592506490.27 startTimestamp=2020/06/18 13:54:50 CDT \n'
D Thu-13:54:54 - starting TAXI to position
D Thu-13:54:54 - starting FLY
H031_D100_att02_35p00C_0003
I Thu-13:54:54 - AD_Acquire starting
I Thu-13:54:54 - file_path = /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0003/
I Thu-13:54:54 - calling full_acquire_procedure()
D Thu-13:54:54 - before update_metadata_prescan()
I Thu-13:54:54 - detNum=46, det_pars={'ccdHardwareColSize': 512, 'ccdHardwareRowSize': 1024, 'ccdxsense': 1, 'ccdzsense': 1, 'harmonic': 1, 'dpix': 0.076, 'saturation': 3, 'adupphot': 1.0, 'efficiency': 1.0, 'gain': 1, 'blemish': 1, 'flatfield': 0, 'distortion': 0, 'parasitic': 0, 'lld': 0, 'manufacturer': 'RIGAKU500K_NoGap'}
D Thu-13:54:54 - after update_metadata_prescan()
D Thu-13:54:54 - supplied metadata = {'ARun_number': 'H031_D100_att02_35p00C_0003', 'plan_args': {'detector_name': 'rigaku', 'acquire_time': 0.1, 'acquire_period': 0.11, 'num_images': 100000, 'file_name': 'H031_D100_att02_35p00C_0003', 'submit_xpcs_job': 'True', 'path': '/home/8-id-i/2020-2/comm202006/'}}
D Thu-13:54:54 - file_name = H031_D100_att02_35p00C_0003
D Thu-13:54:54 - file_path = /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0003/
D Thu-13:54:54 - metadata = {'file_name': 'H031_D100_att02_35p00C_0003', 'file_path': '/home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0003/', 'ARun_number': 'H031_D100_att02_35p00C_0003', 'plan_args': {'detector_name': 'rigaku', 'acquire_time': 0.1, 'acquire_period': 0.11, 'num_images': 100000, 'file_name': 'H031_D100_att02_35p00C_0003', 'submit_xpcs_job': 'True', 'path': '/home/8-id-i/2020-2/comm202006/'}}
I Thu-13:54:54 - scaler should be autocounting now
D Thu-13:54:54 - before count()


Transient Scan ID: 6970     Time: 2020-06-18 13:54:54
Persistent Unique Scan ID: '8edb4528-d236-4b6c-a5b7-b3177df2199b'
New stream: 'baseline'
New stream: 'aps_current_monitor'
New stream: 'Timebase_monitor'


 folder ============= H031_D100_att02_35p00C_0003 




 fname ============= H031_D100_att02_35p00C_0003_00001-100000.bin 


H031_D100_att02_35p00C_0003/H031_D100_att02_35p00C_0003_00001-100000.bin
New stream: 'pind1_monitor'
New stream: 'pind2_monitor'
New stream: 'Atten1_monitor'
New stream: 'Atten2_monitor'
New stream: 'lakeshore_loop1_temperature_monitor'
New stream: 'lakeshore_loop1_target_monitor'
New stream: 'primary'                                                                                                                
+-----------+------------+
|   seq_num |       time |
+-----------+------------+
|         1 | 13:54:57.6 |
D Thu-13:54:57 - after count()
HDF5 workflow file name: /home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0003/H031_D100_att02_35p00C_0003_0001-100000.hdf
+-----------+------------+
generator raster_acq ['8edb4528'] (scan num: 6970)
I Thu-13:54:57 - DM workflow kickoff starting: analysis:True  file:/home/8-id-i/2020-2/comm202006/H031_D100_att02_35p00C_0003/H031_D100_att02_35p00C_0003_0001-100000.hdf
I Thu-13:54:58 - DM workflow kickoff done
I Thu-13:54:58 - b'id=869b6b23-0f6e-4721-866f-096af4a27a81 owner=8idiuser status=pending startTime=1592506498.06 startTimestamp=2020/06/18 13:54:58 CDT \n'
/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/epics/ca.py:1524: UserWarning: ca.get('8idiAERO:PSOFly1:startPos.VAL') timed out after 10.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/epics/ca.py:1524: UserWarning: ca.get('8idiAERO:PSOFly1:endPos.VAL') timed out after 10.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/epics/ca.py:1524: UserWarning: ca.get('8idiAERO:PSOFly1:slewSpeed.VAL') timed out after 10.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
Run aborted
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1330, in _run
    stashed_exception or resp)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1307, in __call__
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1162, in baseline_wrapper
    return (yield from plan_mutator(plan, insert_baseline))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 861, in fly_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_comm202006.py", line 67, in raster_acq
    yield from flyscan_spinner(10, 11, 0.1)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/flyscan.py", line 20, in flyscan_spinner
    yield from flyscan.setup(start_pos, end_pos, fly_speed)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/devices/fly.py", line 53, in setup
    self.slew_speed, slew_speed,
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 258, in mv
    yield Msg('wait', None, group=group)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  [Previous line repeated 2 more times]
bluesky.utils.FailedStatus: Status(obj=EpicsSignal(read_pv='8idiAERO:PSOFly1:slewSpeed.VAL', name='flyscan_slew_speed', parent='flyscan', value=0.1, timestamp=1592506497.8970635, tolerance=1e-05, auto_monitor=False, string=False, write_pv='8idiAERO:PSOFly1:slewSpeed.VAL', limits=False, put_complete=False), done=True, success=False)
---------------------------------------------------------------------------
FailedStatus                              Traceback (most recent call last)
<ipython-input-63-9425a763c4b5> in <module>
----> 1 RE(raster_acq())

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    793             self._task_fut.add_done_callback(set_blocking_event)
    794 
--> 795         self._resume_task(init_func=_build_task)
    796 
    797         if self._interrupted:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _resume_task(self, init_func)
    917                     if (exc is not None
    918                             and not isinstance(exc, _RunEnginePanic)):
--> 919                         raise exc
    920 
    921     def install_suspender(self, suspender):

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1486             exit_reason = str(err)
   1487             self.log.exception("Run aborted")
-> 1488             raise err
   1489         finally:
   1490             if not exit_reason:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1328                         try:
   1329                             msg = self._plan_stack[-1].throw(
-> 1330                                 stashed_exception or resp)
   1331                         except Exception as e:
   1332                             # The current plan did not handle it,

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1305         plan = monitor_during_wrapper(plan, self.monitors)
   1306         plan = baseline_wrapper(plan, self.baseline)
-> 1307         return (yield from plan)
   1308 
   1309 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1160         return (yield from plan)
   1161     else:
-> 1162         return (yield from plan_mutator(plan, insert_baseline))
   1163 
   1164 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    859     plan1 = plan_mutator(plan, insert_after_open)
    860     plan2 = plan_mutator(plan1, insert_before_close)
--> 861     return (yield from plan2)
    862 
    863 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_comm202006.py in raster_acq(areadet, file_header, acq_rep, sample_name, Temp_list, att_value)
     65             if FLY_YES_NO == True:
     66                 logger.info('Running the Fly Stage')
---> 67                 yield from flyscan_spinner(10, 11, 0.1)
     68 
     69             print(acq_name)

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/flyscan.py in flyscan_spinner(start_pos, end_pos, fly_speed)
     18 # flyscan_setup FLY_START_POS FLY_START_POS+2.5*FLY_SPEED FLY_SPEED   ##start,end,speed in mm/sec
     19 def flyscan_spinner(start_pos, end_pos, fly_speed):
---> 20     yield from flyscan.setup(start_pos, end_pos, fly_speed)
     21     yield from bps.abs_set(flyscan, "taxi", wait=True)
     22     yield from bps.abs_set(flyscan, "fly", wait=False)

~/.ipython-bluesky/profile_bluesky/startup/instrument/devices/fly.py in setup(self, start_pos, end_pos, slew_speed)
     51             self.start_pos, start_pos,
     52             self.end_pos, end_pos,
---> 53             self.slew_speed, slew_speed,
     54         )
     55 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/plan_stubs.py in mv(group, *args, **kwargs)
    256         ret = yield Msg('set', obj, val, group=group, **kwargs)
    257         status_objects.append(ret)
--> 258     yield Msg('wait', None, group=group)
    259     return tuple(status_objects)
    260 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

FailedStatus: Status(obj=EpicsSignal(read_pv='8idiAERO:PSOFly1:slewSpeed.VAL', name='flyscan_slew_speed', parent='flyscan', value=0.1, timestamp=1592506497.8970635, tolerance=1e-05, auto_monitor=False, string=False, write_pv='8idiAERO:PSOFly1:slewSpeed.VAL', limits=False, put_complete=False), done=True, success=False)

/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/epics/ca.py:1524: UserWarning: ca.get('8idiAERO:aero:c0:m1.TDIR') timed out after 10.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
In [64]:                                           
```

</details>

**Comment by prjemian** [comment]
It's not obvious why setting the slew speed caused this error.  Is there a limitation that we are not checking such as the EPICS support is busy and slew speed cannot be changed at that time?  Worked two times before.  

I'm suspicious of network repairs that were underway today.  IT reported problems with some network switches ~11:30.  I was disconnected from 9-ID at 11:19 this morning by that problem.

Can you try again and see if the error happens again?

**Comment by qzhang234** [comment]
I just tried it and it was the same problem. Also it stopped at the exactly the third acquisition just like last time.

Maybe we need something that waits for the fly stage motion to complete before moving on to the next acquisition in the `for` loop?

**Comment by qzhang234** [comment]
I fixed the bug. It was on my side. I set the fly from 10 to 11 and speed of 0.1 so the fly is still going when it hits the next `taxi` command. That caused confusion and eventually crashed the scan. I was surprised that it even let me run the first two.

Closing the issue.
