### ISSUE TITLE
Changing Rigaku Acquisition Trigger from BNC to Web Signal

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#183]
@prjemian Nakaye recommended changing the acquisition start signal of Rigaku from Unidig2Bo7 to web signal. I had it implemented in Spec but I'm not sure how to do it in Bluesky. Any suggestions?

<img width="711" alt="Screen Shot 2020-06-27 at 3 02 17 PM" src="https://user-images.githubusercontent.com/48140482/85931105-69012580-b887-11ea-943e-acd192a6c89f.png">

**Comment by prjemian** [comment]
Following the example in these lines: https://github.com/aps-8id-dys/ipython-8idiuser/blob/ee75d6d8382767a4e199a2ec9ed969350476cf15/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py#L168-L169

perhaps this:

```
cmd = f"echo EXPOSURE | nc rigaku1.xray.aps.anl.gov 10000" 
self.unix_process.put(cmd)
```

----

Note, we know that `rigaku1` is the same as the IP number you gave (164.54.116.83):

```
snow% nslookup rigaku1.xray.aps.anl.gov
Server:         164.54.116.205
Address:        164.54.116.205#53

Name:   rigaku1.xray.aps.anl.gov
Address: 164.54.116.83
```

**Comment by prjemian** [comment]
To wait for that `.put()` to finish before proceeding to the next step, this addition should wait:

    self.unix_process.put(cmd, put_complete =True)

**Comment by qzhang234** [comment]
Thanks! I'll give this a spin. If it works I'll close this issue.

**Comment by prjemian** [comment]
Slight correction.  Since there is not formatted value in the `cmd`, no need to uee an_f_ string.  Replace

```
cmd = f"echo EXPOSURE | nc rigaku1.xray.aps.anl.gov 10000" 
self.unix_process.put(cmd, put_complete=True)
```

with this:

```
self.unix_process.put(
    "echo EXPOSURE | nc rigaku1.xray.aps.anl.gov 10000",
    put_complete=True)
```

Perhaps this is clearer to read, as well.

**Comment by prjemian** [comment]
Also, with this change in how the Rigaku is triggered, you might re-examine the commands we added at the start of `trigger()`:

```
        # Tell Rigaku to stop acquisition and wait until it's ready
        self.acquire_start.put(0)
        while self.acquire_complete.get() in (1,'High'):
            time.sleep(0.1)
```

Is this still relevant?

**Comment by qzhang234** [comment]
@prjemian The above code returned with an error:

<details>
<summary> Error Message on Terminal </summary>

```

In [4]: %run -m bp_CPMV                                                                                                       

In [5]: _ = RE(multi_capil())                                                                                                 
Q094_QD-Dec-2_att00_0001                                                                                                      
Run aborted                                                                                                                   
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1353, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1307, in __call__
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1162, in baseline_wrapper
    return (yield from plan_mutator(plan, insert_baseline))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 861, in fly_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py", line 88, in multi_capil
    yield from repeat_acq(sample_name='QD-Dec-2',att_value=0,acq_rep=2,samx_cen=-2.8,samz_cen=2)
  File "/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py", line 73, in repeat_acq
    md={})
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 305, in AD_Acquire
    return (yield from full_acquire_procedure(md=md))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 952, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 950, in inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 273, in full_acquire_procedure
    yield from inner_count([areadet], md=_md)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 232, in inner_count
    yield from bps.trigger(obj, group=grp)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 429, in trigger
    ret = yield Msg('trigger', obj, group=group)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  [Previous line repeated 4 more times]
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1413, in _run
    new_response = await coro(msg)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1940, in _trigger
    ret = msg.obj.trigger(*msg.args, **kwargs)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py", line 173, in trigger
    put_complete=True)
TypeError: put() got an unexpected keyword argument 'put_complete'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-e00c4c348150> in <module>
----> 1 _ = RE(multi_capil())

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    793             self._task_fut.add_done_callback(set_blocking_event)
    794 
--> 795         self._resume_task(init_func=_build_task)
    796 
    797         if self._interrupted:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _resume_task(self, init_func)
    917                     if (exc is not None
    918                             and not isinstance(exc, _RunEnginePanic)):
--> 919                         raise exc
    920 
    921     def install_suspender(self, suspender):

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1486             exit_reason = str(err)
   1487             self.log.exception("Run aborted")
-> 1488             raise err
   1489         finally:
   1490             if not exit_reason:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1351                     else:
   1352                         try:
-> 1353                             msg = self._plan_stack[-1].send(resp)
   1354                         # We have exhausted the top generator
   1355                         except StopIteration:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1305         plan = monitor_during_wrapper(plan, self.monitors)
   1306         plan = baseline_wrapper(plan, self.baseline)
-> 1307         return (yield from plan)
   1308 
   1309 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1160         return (yield from plan)
   1161     else:
-> 1162         return (yield from plan_mutator(plan, insert_baseline))
   1163 
   1164 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    859     plan1 = plan_mutator(plan, insert_after_open)
    860     plan2 = plan_mutator(plan1, insert_before_close)
--> 861     return (yield from plan2)
    862 
    863 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py in multi_capil()
     86 
     87     # yield from bps.mv(samplestage.x, -2.8)
---> 88     yield from repeat_acq(sample_name='QD-Dec-2',att_value=0,acq_rep=2,samx_cen=-2.8,samz_cen=2)
     89 
     90     yield from bps.mv(samplestage.x, 0.2)

/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py in repeat_acq(areadet, file_header, acq_rep, sample_name, Temp_list, att_value, FLY_YES_NO, samx_cen, samz_cen)
     71             atten=None,
     72             path='/home/8-id-i/2020-2/comm202006/',
---> 73             md={})
     74 
     75     bec.enable_plots()

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in AD_Acquire(areadet, acquire_time, acquire_period, num_images, file_name, submit_xpcs_job, atten, path, md)
    303 
    304     logger.info("calling full_acquire_procedure()")
--> 305     return (yield from full_acquire_procedure(md=md))

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1044                 plan = gen_func(*inner_args, **inner_kwargs)
   1045                 plan = wrapper(plan, *args, **kwargs)
-> 1046                 return (yield from plan)
   1047             return dec_inner
   1048         return dec

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in stage_wrapper(plan, devices)
    950         return (yield from plan)
    951 
--> 952     return (yield from finalize_wrapper(inner(), unstage_devices()))
    953 
    954 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    507     cleanup = True
    508     try:
--> 509         ret = yield from plan
    510     except GeneratorExit:
    511         cleanup = False

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in inner()
    948     def inner():
    949         yield from stage_devices()
--> 950         return (yield from plan)
    951 
    952     return (yield from finalize_wrapper(inner(), unstage_devices()))

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1044                 plan = gen_func(*inner_args, **inner_kwargs)
   1045                 plan = wrapper(plan, *args, **kwargs)
-> 1046                 return (yield from plan)
   1047             return dec_inner
   1048         return dec

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in full_acquire_procedure(md)
    271         logger.debug("before count()")
    272         # yield from bp.count([areadet], md=md)
--> 273         yield from inner_count([areadet], md=_md)
    274         logger.debug("after count()")
    275 

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in inner_count(devices, md)
    230             if hasattr(obj, 'trigger'):
    231                 no_wait = False
--> 232                 yield from bps.trigger(obj, group=grp)
    233         if areadet.cam.EXT_TRIGGER > 0:
    234             yield from soft_glue.start_trigger()

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/plan_stubs.py in trigger(obj, group, wait)
    427     msg : Msg
    428     """
--> 429     ret = yield Msg('trigger', obj, group=group)
    430     if wait:
    431         yield Msg('wait', None, group=group)

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1411                         # exceptions (coming in via throw) can be
   1412                         # raised
-> 1413                         new_response = await coro(msg)
   1414 
   1415                     # special case `CancelledError` and let the outer

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _trigger(self, msg)
   1938         kwargs = dict(msg.kwargs)
   1939         group = kwargs.pop('group', None)
-> 1940         ret = msg.obj.trigger(*msg.args, **kwargs)
   1941         p_event = asyncio.Event(loop=self.loop)
   1942         pardon_failures = self._pardon_failures

~/.ipython-bluesky/profile_bluesky/startup/instrument/devices/rigaku_ufxc.py in trigger(self)
    171         self.unix_process.put(
    172             "echo EXPOSURE | nc rigaku1.xray.aps.anl.gov 10000",
--> 173             put_complete=True)
    174 
    175         # Getting ready to watch acquisition complete

TypeError: put() got an unexpected keyword argument 'put_complete'

```

</details>

**Comment by qzhang234** [comment]
@prjemian I further modified function `trigger` to remove the flip of BNC level to avoid confusion. I also added a 0.1 s wait before and after Bluesky receives the ready signal from Rigaku to (hopefully) further improve the stability of the code. 

So here's the code before and after the change:

<details>
<summary> Before </summary>

```
    def trigger(self):
        # Tell Rigaku to stop acquisition and wait until it's ready
        self.acquire_start.put(0)
        while self.acquire_complete.get() in (1,'High'):
            time.sleep(0.1)

        # Getting ready to watch acquisition complete
        status = DeviceStatus(self)

        def watch_acquire(value,old_value,**kwargs):
            if value == 1 and old_value == 0:
                self.acquire_start.put(0)
                self.acquire_complete.clear_sub(watch_acquire)
                status._finished()

        # Start acquisition
        self.acquire_complete.subscribe(watch_acquire)
        self.acquire_start.put(1)
        time.sleep(0.1)     # could be shorter, this works now
        self.acquire_start.put(0)  # Stop acquisition

```
</details>


<details>
<summary> After </summary>

```

    def trigger(self):
        # Tell Rigaku to stop acquisition and wait until it's ready
        # self.acquire_start.put(0)
        while self.acquire_complete.get() in (1,'High'):
            time.sleep(0.1)
            
        # Getting ready to watch acquisition complete
        status = DeviceStatus(self)

        def watch_acquire(value,old_value,**kwargs):
            if value == 1 and old_value == 0:
                # self.acquire_start.put(0)
                self.acquire_complete.clear_sub(watch_acquire)
                status._finished()

        # Start acquisition
        self.acquire_complete.subscribe(watch_acquire)
        time.sleep(0.1)  # QZ 06/28/20: No reason. Put it there to improve stability
        # self.acquire_start.put(1)
        self.unix_process.put(
            "echo EXPOSURE | nc rigaku1.xray.aps.anl.gov 10000")
        time.sleep(0.1)     # could be shorter, this works now
        # self.acquire_start.put(0)  # Stop acquisition

```
</details>

**Comment by prjemian** [comment]
Another view of the differences:
![Clipboard01](https://user-images.githubusercontent.com/2279984/85940630-1f462880-b8e3-11ea-94d7-cbcd13d58894.jpg)

LGTM

**Comment by prjemian** [comment]
Leave this ticket open until you commit the changes (with a commit message that says `fixes #183`) and push.  The issue will close automatically.

**Comment by qzhang234** [comment]
How did you open that? Was that Git plugin in VS Code?

**Comment by prjemian** [comment]
Correct.  Bigger screen view.
![Clipboard01](https://user-images.githubusercontent.com/2279984/85940775-1efa5d00-b8e4-11ea-92f9-08adeb60332a.jpg)

On the left (wherever), select the git branch symbol (number of files changed is shown, this time is 1).  Click on the file changed and the differences show up.

**Comment by qzhang234** [comment]
Bluesky successfully completed 12,000 acquisitions (spanning over ~ 20 hours) after the above-mentioned code fix (changing the 'start-acquisition' signal from BNC to web command and added a 0.1 s delay before and after) was implemented. 

This was a milestone achievement. 

Closing the issue.

<img width="1081" alt="Screen Shot 2020-06-28 at 6 31 50 PM" src="https://user-images.githubusercontent.com/48140482/85961122-ce2f4680-b96d-11ea-97de-00624e723891.png">

**Comment by prjemian** [comment]
Fantastic!
