### ISSUE TITLE
ReadTimeoutError: Failed to read 8idi:scaler1.S8 -- Bluesky crashed after ~ 15000 Measurements

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#192]
@prjemian Bluesky plan crashed after ~ 15,000 measurements. This time I'm not sure it's Bluesky's problem since the error message is very clear: It's complaining about loss of connection with `8idi:scaler1.S8`. I attached a screenshot of the EPICS panel. @sureshnaps Is the I0Mon supposed to be around 0? 

Also @prjemian is it a good idea for Bluesky to crash the scan because it can't read the scalers? Looking at the list of PVs, I can't think of any scaler values listed here being critical to the XPCS analysis. Brian Stephenson would argue otherwise, but both Suresh and I have went through it and I'm sure we both have our two cents on that topic. What's your thought?

<details>
<summary> Error from terminal </summary>

```

C155_TMV_Fly0p04_att00_5060
HDF5 workflow file name: /home/8-id-i/2020-2/qzhang202006/C155_TMV_Fly0p04_att00_5060/C155_TMV_Fly0p04_att00_5060_0001-100000.hdf    
C155_TMV_Fly0p04_att00_5061                                                                                                          
HDF5 workflow file name: /home/8-id-i/2020-2/qzhang202006/C155_TMV_Fly0p04_att00_5061/C155_TMV_Fly0p04_att00_5061_0001-100000.hdf    
C155_TMV_Fly0p04_att00_5062
HDF5 workflow file name: /home/8-id-i/2020-2/qzhang202006/C155_TMV_Fly0p04_att00_5062/C155_TMV_Fly0p04_att00_5062_0001-100000.hdf    
C155_TMV_Fly0p04_att00_5063
/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/epics/ca.py:1524: UserWarning: ca.get('8idi:scaler1.S8') timed out after 2.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
Run aborted
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1353, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1307, in __call__
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1162, in baseline_wrapper
    return (yield from plan_mutator(plan, insert_baseline))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 861, in fly_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py", line 90, in multi_capil
    yield from repeat_acq(sample_name='TMV_Fly0p04',att_value=0,acq_rep=10000,FLY_YES_NO=True,samx_cen=-4,samz_cen=z0)
  File "/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py", line 73, in repeat_acq
    md={})
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 305, in AD_Acquire
    return (yield from full_acquire_procedure(md=md))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 952, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 950, in inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 254, in full_acquire_procedure
    yield from update_metadata_prescan()
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py", line 201, in update_metadata_prescan
    dm_pars.I0mon, I0Mon.get(),
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/ophyd/signal.py", line 1088, in get
    self._read_pv, timeout, connection_timeout, as_string, form)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/ophyd/signal.py", line 1051, in _get_with_timeout
    f"Failed to read {pv.pvname} "
ophyd.signal.ReadTimeoutError: Failed to read 8idi:scaler1.S8 within 2.0 sec
---------------------------------------------------------------------------
ReadTimeoutError                          Traceback (most recent call last)
<ipython-input-24-e00c4c348150> in <module>
----> 1 _ = RE(multi_capil())

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    793             self._task_fut.add_done_callback(set_blocking_event)
    794 
--> 795         self._resume_task(init_func=_build_task)
    796 
    797         if self._interrupted:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _resume_task(self, init_func)
    917                     if (exc is not None
    918                             and not isinstance(exc, _RunEnginePanic)):
--> 919                         raise exc
    920 
    921     def install_suspender(self, suspender):

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1486             exit_reason = str(err)
   1487             self.log.exception("Run aborted")
-> 1488             raise err
   1489         finally:
   1490             if not exit_reason:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1351                     else:
   1352                         try:
-> 1353                             msg = self._plan_stack[-1].send(resp)
   1354                         # We have exhausted the top generator
   1355                         except StopIteration:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1305         plan = monitor_during_wrapper(plan, self.monitors)
   1306         plan = baseline_wrapper(plan, self.baseline)
-> 1307         return (yield from plan)
   1308 
   1309 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1160         return (yield from plan)
   1161     else:
-> 1162         return (yield from plan_mutator(plan, insert_baseline))
   1163 
   1164 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    859     plan1 = plan_mutator(plan, insert_after_open)
    860     plan2 = plan_mutator(plan1, insert_before_close)
--> 861     return (yield from plan2)
    862 
    863 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py in multi_capil()
     88 
     89     yield from repeat_acq(sample_name='TMV',att_value=0,acq_rep=10000,samx_cen=-4,samz_cen=z0)
---> 90     yield from repeat_acq(sample_name='TMV_Fly0p04',att_value=0,acq_rep=10000,FLY_YES_NO=True,samx_cen=-4,samz_cen=z0)
     91 
     92     # yield from repeat_acq(sample_name='D100_NoFly',att_value=2,acq_rep=5,samx_cen=9.4,samz_cen=z0)

/home/beams10/8IDIUSER/bluesky_data/2020/2020-2/bp_CPMV.py in repeat_acq(areadet, file_header, acq_rep, sample_name, Temp_list, att_value, FLY_YES_NO, samx_cen, samz_cen)
     71             atten=None,
     72             path='/home/8-id-i/2020-2/qzhang202006/',
---> 73             md={})
     74 
     75     bec.enable_plots()

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in AD_Acquire(areadet, acquire_time, acquire_period, num_images, file_name, submit_xpcs_job, atten, path, md)
    303 
    304     logger.info("calling full_acquire_procedure()")
--> 305     return (yield from full_acquire_procedure(md=md))

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1044                 plan = gen_func(*inner_args, **inner_kwargs)
   1045                 plan = wrapper(plan, *args, **kwargs)
-> 1046                 return (yield from plan)
   1047             return dec_inner
   1048         return dec

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in stage_wrapper(plan, devices)
    950         return (yield from plan)
    951 
--> 952     return (yield from finalize_wrapper(inner(), unstage_devices()))
    953 
    954 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    507     cleanup = True
    508     try:
--> 509         ret = yield from plan
    510     except GeneratorExit:
    511         cleanup = False

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in inner()
    948     def inner():
    949         yield from stage_devices()
--> 950         return (yield from plan)
    951 
    952     return (yield from finalize_wrapper(inner(), unstage_devices()))

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1044                 plan = gen_func(*inner_args, **inner_kwargs)
   1045                 plan = wrapper(plan, *args, **kwargs)
-> 1046                 return (yield from plan)
   1047             return dec_inner
   1048         return dec

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in full_acquire_procedure(md)
    252     def full_acquire_procedure(md={}):
    253         logger.debug("before update_metadata_prescan()")
--> 254         yield from update_metadata_prescan()
    255         logger.debug("after update_metadata_prescan()")
    256 

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/xpcs_acquire.py in update_metadata_prescan()
    199         yield from bps.mv(
    200             # Reg 123-127 in order
--> 201             dm_pars.I0mon, I0Mon.get(),
    202             dm_pars.burst_mode_state, 0,   # 0 for Lambda, other detector might use this
    203             dm_pars.number_of_bursts, 0,   # 0 for Lambda, other detector might use this

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/ophyd/signal.py in get(self, as_string, timeout, connection_timeout, form, **kwargs)
   1086 
   1087         info = self._get_with_timeout(
-> 1088             self._read_pv, timeout, connection_timeout, as_string, form)
   1089 
   1090         value = info.pop('value')

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/ophyd/signal.py in _get_with_timeout(self, pv, timeout, connection_timeout, as_string, form)
   1049         if info is None:
   1050             raise ReadTimeoutError(
-> 1051                 f"Failed to read {pv.pvname} "
   1052                 f"within {timeout:.2} sec")
   1053 

ReadTimeoutError: Failed to read 8idi:scaler1.S8 within 2.0 sec

In [25]:                                                                                                                             

```

</details>

**Comment by prjemian** [comment]
The value of `I0Mon` is retrieved from the scaler during `AD_Acquire()` and copied to to one of the data management number registers:  https://github.com/aps-8id-dys/ipython-8idiuser/blob/b3c37322e1fd3639bc592ce824dd662421a0f244/profile_bluesky/startup/instrument/plans/xpcs_acquire.py#L201

This is the data management number register: https://github.com/aps-8id-dys/ipython-8idiuser/blob/b3c37322e1fd3639bc592ce824dd662421a0f244/profile_bluesky/startup/instrument/devices/data_management.py#L62

**Comment by prjemian** [comment]
It would be possible to _wrap_ this code: https://github.com/aps-8id-dys/ipython-8idiuser/blob/b3c37322e1fd3639bc592ce824dd662421a0f244/profile_bluesky/startup/instrument/plans/xpcs_acquire.py#L199-L206

within a `try..except` clause which would permit this copy operation to fail but not block the scan.  It should log the information from the situation.  The `try..except` clause does not solve the very rare problem here but it minimizes the trouble it causes.

Works like this:

```
        try:
            yield from bps.mv(
                # Reg 123-127 in order
                dm_pars.I0mon, I0Mon.get(),
                dm_pars.burst_mode_state, 0,   # 0 for Lambda, other detector might use this
                dm_pars.number_of_bursts, 0,   # 0 for Lambda, other detector might use this
                dm_pars.first_usable_burst, 0,   # 0 for Lambda, other detector might use this
                dm_pars.last_usable_burst, 0,   # 0 for Lambda, other detector might use this
            )
        except ophyd.signal.ReadTimeoutError as exc:
            logger.warn("EPICS ReadTimeoutError from scaler (ignoring): %s", str(exc))
```

**Comment by prjemian** [comment]
Might want to separate the `I0Mon` from the other actions in `bps.mv()` so that they will always happen.  After all, they are **constants** here.

**Comment by prjemian** [comment]
At the very least, the timeout of 2.0 seconds could be increased.  This would allow a longer time only if needed.

**Comment by prjemian** [comment]
@qzhang234 : Still a problem to solve?  Are #192, #194, & #195 related to the same problem?

**Comment by qzhang234** [comment]
Not quite. However all of these are Bluesky repeatability problems that are a bit hard to reproduce. What should we do with them? Maybe close them all and reopen when any of them resurface during our test next month?

**Comment by prjemian** [comment]
Agree.  And, if we can remember, reference back to the previous issue.

**Comment by prjemian** [comment]
I suggest you close as "wontfix" for now.

**Comment by qzhang234** [comment]
How do I do that?

**Comment by prjemian** [comment]
There is a list of labels in the GitHub web page for this issue.  The list is on the right side, just below the list of assignees.  The list is alphabetical so `wontfix` is near/at the bottom.  Select this and it will be added to any other labels for the issue.  

This leaves a marker saying the issue was not fixed.  Your text at (or near) the time the label was applied will say why.
