### ISSUE TITLE
'lup' Crashed After Adding 'md'

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-dys/ipython-8idiuser#197]
@prjemian `lup` crashed after adding `md` with the intention of listing scans according to the motor it was moved. For now I removed the `md` part and `lup` works again, but would be nice to know how to fix it.

<details>
<summary> Terminal Output </summary>

```

In [16]: RE(lup(pind4,samplestage.z,-0.1,0.1,11))                                                                         
Run aborted
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1353, in _run
    msg = self._plan_stack[-1].send(resp)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1307, in __call__
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1162, in baseline_wrapper
    return (yield from plan_mutator(plan, insert_baseline))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 803, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 861, in fly_during_wrapper
    return (yield from plan2)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 170, in plan_mutator
    raise ex
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 123, in plan_mutator
    msg = plan_stack[-1].send(ret)
  File "/home/beams/8IDIUSER/.ipython-bluesky/profile_bluesky/startup/instrument/plans/alignments.py", line 91, in lup
    md=md)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/plans.py", line 1390, in rel_scan
    return (yield from inner_rel_scan())
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1120, in reset_positions_wrapper
    reset()))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 509, in finalize_wrapper
    ret = yield from plan
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 1046, in dec_inner
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1075, in relative_set_wrapper
    return (yield from plan)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 245, in msg_mutator
    ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 141, in single_gen
    return (yield msg)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 141, in single_gen
    return (yield msg)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 78, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 141, in single_gen
    return (yield msg)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py", line 195, in plan_mutator
    inner_ret = yield msg
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1413, in _run
    new_response = await coro(msg)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 1598, in _open_run
    new_uid = await current_run.open_run(msg)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/bundlers.py", line 53, in open_run
    await self.emit(DocumentNames.start, doc)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 2260, in emit
    self.emit_sync(name, doc)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 2257, in emit_sync
    self.dispatcher.process(name, doc)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py", line 2280, in process
    exceptions = self.cb_registry.process(name, name.name, doc)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 352, in process
    func(*args, **kwargs)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py", line 433, in __call__
    return mtd(*args, **kwargs)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/databroker/v1.py", line 964, in insert
    self._serializer(name, doc)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/suitcase/mongo_normalized/__init__.py", line 91, in __call__
    sanitized_doc = event_model.sanitize_doc(doc)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/event_model/__init__.py", line 2064, in sanitize_doc
    return json.loads(json.dumps(doc, cls=NumpyEncoder))
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/event_model/__init__.py", line 2090, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2020_5/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type EpicsMotor is not JSON serializable
Failed to close run <bluesky.bundlers.RunBundler object at 0x7f40ec51dd10>.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-be4b17b89f37> in <module>
----> 1 RE(lup(pind4,samplestage.z,-0.1,0.1,11))

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    793             self._task_fut.add_done_callback(set_blocking_event)
    794 
--> 795         self._resume_task(init_func=_build_task)
    796 
    797         if self._interrupted:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _resume_task(self, init_func)
    917                     if (exc is not None
    918                             and not isinstance(exc, _RunEnginePanic)):
--> 919                         raise exc
    920 
    921     def install_suspender(self, suspender):

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1486             exit_reason = str(err)
   1487             self.log.exception("Run aborted")
-> 1488             raise err
   1489         finally:
   1490             if not exit_reason:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1351                     else:
   1352                         try:
-> 1353                             msg = self._plan_stack[-1].send(resp)
   1354                         # We have exhausted the top generator
   1355                         except StopIteration:

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1305         plan = monitor_during_wrapper(plan, self.monitors)
   1306         plan = baseline_wrapper(plan, self.baseline)
-> 1307         return (yield from plan)
   1308 
   1309 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1160         return (yield from plan)
   1161     else:
-> 1162         return (yield from plan_mutator(plan, insert_baseline))
   1163 
   1164 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    801     plan1 = plan_mutator(plan, insert_after_open)
    802     plan2 = plan_mutator(plan1, insert_before_close)
--> 803     return (yield from plan2)
    804 
    805 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    859     plan1 = plan_mutator(plan, insert_after_open)
    860     plan2 = plan_mutator(plan1, insert_before_close)
--> 861     return (yield from plan2)
    862 
    863 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    168                     continue
    169                 else:
--> 170                     raise ex
    171         # if inserting / mutating, put new generator on the stack
    172         # and replace the current msg with the first element from the

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    121             ret = result_stack.pop()
    122             try:
--> 123                 msg = plan_stack[-1].send(ret)
    124             except StopIteration as e:
    125                 # discard the exhausted generator

~/.ipython-bluesky/profile_bluesky/startup/instrument/plans/alignments.py in lup(scaler_name, motor_name, pos_start, pos_stop, num_pts, md_input)
     89         pos_stop,
     90         num_pts,
---> 91         md=md) 
     92     yield from bb()

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/plans.py in rel_scan(detectors, num, per_step, md, *args)
   1388                                 per_step=per_step, md=_md))
   1389 
-> 1390     return (yield from inner_rel_scan())
   1391 
   1392 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1044                 plan = gen_func(*inner_args, **inner_kwargs)
   1045                 plan = wrapper(plan, *args, **kwargs)
-> 1046                 return (yield from plan)
   1047             return dec_inner
   1048         return dec

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in reset_positions_wrapper(plan, devices)
   1118 
   1119     return (yield from finalize_wrapper(plan_mutator(plan, insert_reads),
-> 1120                                         reset()))
   1121 
   1122 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    507     cleanup = True
    508     try:
--> 509         ret = yield from plan
    510     except GeneratorExit:
    511         cleanup = False

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1044                 plan = gen_func(*inner_args, **inner_kwargs)
   1045                 plan = wrapper(plan, *args, **kwargs)
-> 1046                 return (yield from plan)
   1047             return dec_inner
   1048         return dec

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in relative_set_wrapper(plan, devices)
   1073     plan = plan_mutator(plan, insert_reads)
   1074     plan = msg_mutator(plan, rewrite_pos)
-> 1075     return (yield from plan)
   1076 
   1077 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in msg_mutator(plan, msg_proc)
    243                 ret = None
    244                 continue
--> 245             ret = yield msg
    246         except StopIteration as e:
    247             return e.value

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in single_gen(msg)
    139         the input message
    140     '''
--> 141     return (yield msg)
    142 
    143 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in single_gen(msg)
    139         the input message
    140     '''
--> 141     return (yield msg)
    142 
    143 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     76             # if we have a stashed exception, pass it along
     77             try:
---> 78                 msg = plan_stack[-1].throw(exception)
     79             except StopIteration as e:
     80                 # discard the exhausted generator

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in single_gen(msg)
    139         the input message
    140     '''
--> 141     return (yield msg)
    142 
    143 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    193         try:
    194             # yield out the 'current message' and collect the return
--> 195             inner_ret = yield msg
    196         except GeneratorExit:
    197             # special case GeneratorExit.  We must clean up all of our plans

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1411                         # exceptions (coming in via throw) can be
   1412                         # raised
-> 1413                         new_response = await coro(msg)
   1414 
   1415                     # special case `CancelledError` and let the outer

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in _open_run(self, msg)
   1596             loop=self.loop)
   1597 
-> 1598         new_uid = await current_run.open_run(msg)
   1599         self._run_start_uids.append(new_uid)
   1600         return new_uid

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/bundlers.py in open_run(self, msg)
     51 
     52         doc = dict(uid=self._run_start_uid, time=ttime.time(), **self._md)
---> 53         await self.emit(DocumentNames.start, doc)
     54         doc_logger.debug("[start] document is emitted (run_uid=%r)", self._run_start_uid,
     55                          extra={'doc_name': 'start',

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in emit(self, name, doc)
   2258 
   2259     async def emit(self, name, doc):
-> 2260         self.emit_sync(name, doc)
   2261 
   2262 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in emit_sync(self, name, doc)
   2255         "Process blocking callbacks and schedule non-blocking callbacks."
   2256         schema_validators[name].validate(doc)
-> 2257         self.dispatcher.process(name, doc)
   2258 
   2259     async def emit(self, name, doc):

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in process(self, name, doc)
   2278         doc : dict
   2279         """
-> 2280         exceptions = self.cb_registry.process(name, name.name, doc)
   2281         for exc, traceback in exceptions:
   2282             warn("A %r was raised during the processing of a %s "

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in process(self, sig, *args, **kwargs)
    350             for cid, func in list(self.callbacks[sig].items()):
    351                 try:
--> 352                     func(*args, **kwargs)
    353                 except ReferenceError:
    354                     self._remove_proxy(func)

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/utils.py in __call__(self, *args, **kwargs)
    431             mtd = self.func
    432         # invoke the callable and return the result
--> 433         return mtd(*args, **kwargs)
    434 
    435     def __eq__(self, other):

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/databroker/v1.py in insert(self, name, doc)
    962             "The method Broker.insert may be removed in a future release of "
    963             "databroker.", PendingDeprecationWarning)
--> 964         self._serializer(name, doc)
    965         # Make a reasonable effort to keep the Catalog in sync with new data.
    966         if name == 'stop':

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/suitcase/mongo_normalized/__init__.py in __call__(self, name, doc)
     89         # Before inserting into mongo, convert any numpy objects into built-in
     90         # Python types compatible with pymongo.
---> 91         sanitized_doc = event_model.sanitize_doc(doc)
     92         return super().__call__(name, sanitized_doc)
     93 

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/event_model/__init__.py in sanitize_doc(doc)
   2062         Python types.
   2063     '''
-> 2064     return json.loads(json.dumps(doc, cls=NumpyEncoder))
   2065 
   2066 

~/.conda/envs/bluesky_2020_5/lib/python3.7/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 
    240 

~/.conda/envs/bluesky_2020_5/lib/python3.7/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

~/.conda/envs/bluesky_2020_5/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

~/.conda/envs/bluesky_2020_5/lib/python3.7/site-packages/event_model/__init__.py in default(self, obj)
   2088                 return obj.item()
   2089             return obj.tolist()
-> 2090         return json.JSONEncoder.default(self, obj)

~/.conda/envs/bluesky_2020_5/lib/python3.7/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181 

TypeError: Object of type EpicsMotor is not JSON serializable

In [17]:                                                      


```

</details>

**Comment by qzhang234** [comment]
`lup` code before and after removing the `md` part:

<details>

<summary>. /instrument/plans/alignment.py  </summary>

```

# QZ added on 2020/06/22

# def lup(scaler_name=None,
#         motor_name=None,
#         pos_start=-0.5,
#         pos_stop=0.5,
#         num_pts=41,
#         md_input={}):  
        
#     md = {}
#     md["plan_name"] = "lup"
#     md["pos_start"] = pos_start
#     md["pos_stop"] = pos_stop
#     md["motor_name"] = motor_name
#     md["num_pts"] = num_pts
#     md["scaler_name"] = scaler_name
#     md.update(md_input)

#     yield from sb() 
#     yield from bp.rel_scan(
#         [scaler_name, lakeshore],
#         motor_name,
#         pos_start,
#         pos_stop,
#         num_pts,
#         md=md) 
#     yield from bb() 


def lup(scaler_name,
        motor_name,
        pos_start,
        pos_stop,
        num_pts):
        
    yield from sb() 
    yield from bp.rel_scan(
        [scaler_name, lakeshore],
        motor_name,
        pos_start,
        pos_stop,
        num_pts) 
    yield from bb() 



```

</details>

**Comment by prjemian** [comment]
This is the reported error: `TypeError: Object of type EpicsMotor is not JSON serializable`.  It comes from this line: `md["motor_name"] = motor_name`.  The real problem here is that `motor_name` is used when the object passed to `lup()` is actually an instance of `EpicsMotor` (not a `str`).

The fix is to (restore the `lup` with `md` support) and:

* replace `motor_name` with `motor`
* use: `md["motor_name"] = motor.name`

Probably will then encounter the same problem with `scaler_name`.  Use same technique to solve it.
